config/routes.rb
Rails.application.routes.draw do
  resources :sales_histories
  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales_histories
end

app/models/sales_history.rb
class SalesHistory < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:company_name, :zip, :address, :tel, :responsible_name)
    end
end

app/controllers/sales_histories_controller.rb
class SalesHistoriesController < ApplicationController
  before_action :set_sales_history, only: [:show, :edit, :update, :destroy]

  # GET /sales_histories
  # GET /sales_histories.json
  def index
    @sales_histories = SalesHistory.all
  end

  # GET /sales_histories/1
  # GET /sales_histories/1.json
  def show
  end

  # GET /sales_histories/new
  def new
    @sales_history = SalesHistory.new
  end

  # GET /sales_histories/1/edit
  def edit
  end

  # POST /sales_histories
  # POST /sales_histories.json
  def create
    @sales_history = SalesHistory.new(sales_history_params)

    respond_to do |format|
      if @sales_history.save
        format.html { redirect_to @sales_history, notice: 'Sales history was successfully created.' }
        format.json { render :show, status: :created, location: @sales_history }
      else
        format.html { render :new }
        format.json { render json: @sales_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_histories/1
  # PATCH/PUT /sales_histories/1.json
  def update
    respond_to do |format|
      if @sales_history.update(sales_history_params)
        format.html { redirect_to @sales_history, notice: 'Sales history was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_history }
      else
        format.html { render :edit }
        format.json { render json: @sales_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_histories/1
  # DELETE /sales_histories/1.json
  def destroy
    @sales_history.destroy
    respond_to do |format|
      format.html { redirect_to sales_histories_url, notice: 'Sales history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_history
      @sales_history = SalesHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_history_params
      params.require(:sales_history).permit(:activity_time, :customer_id, :sales_category, :sales_achievement, :detail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/sales_histories_helper.rb
module SalesHistoriesHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name,t('.company_name') %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :zip,t('.zip')%> %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :address,t('.address') %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel,t('.tel') %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :responsible_name,t('.responsible_name') %><br>
    <%= f.text_field :responsible_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title')%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.company_name')%></th>
      <th><%= t('.zip')%></th>
      <th><%= t('.address')%></th>
      <th><%= t('.tel')%></th>
      <th><%= t('.responsible_name')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.company_name %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.address %></td>
        <td><%= customer.tel %></td>
        <td><%= customer.responsible_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @customer.company_name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @customer.zip %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @customer.tel %>
</p>

<p>
  <strong>Responsible name:</strong>
  <%= @customer.responsible_name %>
</p>

<table>
  <thead>
    <tr>
      <th><%= t('.activity_time')%></th>
      <th><%= t('.customer')%></th>
      <th><%= t('.sales_category')%></th>
      <th><%= t('.sales_achievement')%></th>
      <th><%= t('.detail')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer.sales_histories.each do |sales_history| %>
      <tr>
        <td><%= sales_history.activity_time %></td>
        <td><%= sales_history.customer.company_name %></td>
        <td><%= sales_history.sales_category %></td>
        <td><%= sales_history.sales_achievement %></td>
        <td><%= sales_history.detail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SalesActivity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sales_histories/_form.html.erb
<%= form_for(@sales_history) do |f| %>
  <% if @sales_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_history.errors.count, "error") %> prohibited this sales_history from being saved:</h2>

      <ul>
      <% @sales_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_time,"営業日時" %><br>
    <%= f.datetime_select :activity_time %>
  </div>
  <div class="field">
    <%= f.label :customer_id,"顧客ID" %><br>
<!--     <%# customers = Customer.all %>
    <%# ary=[] %>
    <%# customers.each do|c| %>
      <%# ary << [c.company_name, c.id] %>
    <%# end %>
    <%#= f.select(:customer_id, options_for_select(ary)) %>
 -->    <%= f.collection_select(:customer_id, Customer.all, :id, :company_name) %>
  </div>
  <div class="field">
    <%= f.label :sales_category,"営業区分" %><br>
    <%= f.select(:sales_category, options_for_select(["商品案内","契約","フォロー","クレーム処理","他"],"契約")) %>
  </div>
  <div class="field">
    <%= f.label :sales_achievement,"営業成果" %><br>
    <%= f.select(:sales_achievement, options_for_select(["達成","継続","失敗"],"達成")) %>
  </div>
  <div class="field">
    <%= f.label :detail,"メモ" %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_histories/edit.html.erb
<h1>Editing Sales History</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_history %> |
<%= link_to 'Back', sales_histories_path %>

app/views/sales_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title')%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.activity_time')%></th>
      <th><%= t('.customer')%></th>
      <th><%= t('.sales_category')%></th>
      <th><%= t('.sales_achievement')%></th>
      <th><%= t('.detail')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_histories.each do |sales_history| %>
      <tr>
        <td><%= sales_history.activity_time %></td>
        <td><%= sales_history.customer.company_name %></td>
        <td><%= sales_history.sales_category %></td>
        <td><%= sales_history.sales_achievement %></td>
        <td><%= sales_history.detail %></td>
        <td><%= link_to 'Show', sales_history %></td>
        <td><%= link_to 'Edit', edit_sales_history_path(sales_history) %></td>
        <td><%= link_to 'Destroy', sales_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sales history', new_sales_history_path %>

app/views/sales_histories/new.html.erb
<h1>New Sales History</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_histories_path %>

app/views/sales_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.activity_time')%>:</strong>
  <%= @sales_history.activity_time %>
</p>

<p>
  <strong><%= t('.customer')%>:</strong>
  <%= @sales_history.customer %>
</p>

<p>
  <strong>Sales category:</strong>
  <%= @sales_history.sales_category %>
</p>

<p>
  <strong>Sales achievement:</strong>
  <%= @sales_history.sales_achievement %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @sales_history.detail %>
</p>

<%= link_to 'Edit', edit_sales_history_path(@sales_history) %> |
<%= link_to 'Back', sales_histories_path %>